### ISSUE TITLE
Feature: Add request_total metric

### ISSUE THREAD

**Issue by n5sgg** [slok/go-http-metrics#200]
Hello, we are missing a total request counter. As recommended in [RED](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture) or golden signals, the error rate monitoring is essential.

In [here](https://github.com/slok/go-http-metrics/blob/master/metrics/prometheus/prometheus.go#L77) we would add something like this:
```go
r := &recorder{
	httpRequestTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: cfg.Prefix,
		Subsystem: "http",
		Name:      "request_total",
		Help:      "The number of total HTTP requests.",
	}, []string{cfg.ServiceLabel, cfg.HandlerIDLabel, cfg.MethodLabel, cfg.StatusCodeLabel}),
        ...
}
```

A possible alert using this metric:
```yaml
- alert: HttpHigh5xxErrorRate 
  expr: sum(rate(http_requests_total{status=~"5.*"}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
  for: 1m
  labels:
    severity: critical
  annotations:
    summary: Http high 5xx error rate
    description: "Too many HTTP requests with status 5xx (> 5%) on the server."
```

I'm happy to create a PR for this feature if you agree. Thank you!

**Comment by slok** [comment]
Hi! :wave: 

You can achieve that already, latency histogram metric has this data too, we don't have a second metric so we don't record redundant metrics. [check this section on the readme](https://github.com/slok/go-http-metrics#prometheus-query-examples).

Your alert example would be like this:

```yaml
- alert: HttpHigh5xxErrorRate 
  expr: sum(rate(http_request_duration_seconds_count{status=~"5.*"}[5m])) / sum(rate(http_request_duration_seconds_count[5m])) * 100 > 5
  for: 1m
  labels:
    severity: critical
  annotations:
    summary: Http high 5xx error rate
    description: "Too many HTTP requests with status 5xx (> 5%) on the server."
```

Closing the issue, if you have further doubts, please reopen it or open a new issue.

Thanks!
